apiVersion: apps/v1
kind: Deployment
metadata:
  name: ping
  labels:
    app: ping
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ping
  template:
    metadata:
      labels:
        app: ping
    spec:
      restartPolicy: Always
      containers:
      - name: ping
        image: ghcr.io/mchmarny/grpc-ping:v0.2.1
        ports:
        - containerPort: 50505
        - containerPort: 8080
        env:
        - name: GRPC_PORT
          value: "50505"
        - name: HTTP_PORT
          value: "8080"
        - name: DEBUG
          value: "true"
      

