apiVersion: apps/v1
kind: Deployment
metadata:
  name: ping
  namespace: grpc-lab
  labels:
    app: ping
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ping
  template:
    metadata:
      labels:
        app: ping
        demo: grpc-lab
    spec:
      restartPolicy: Always
      containers:
      - name: ping
        image: ghcr.io/mchmarny/grpc-ping:v0.0.1
        ports:
        - containerPort: 50505
        env:
        - name: ADDRESS
          value: ":50505"
        - name: DEBUG
          value: "true"
      

