name: image on tag

on:  
  push:
    tags:
      - 'v*'

jobs:

  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:

    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: ^1.16

    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Tidy Modules
      run: |
        make tidy

    - name: Config Lint
      id: golangci_config
      uses: andstor/file-existence-action@v1
      with:
        files: .golangci.yaml

    - name: Lint Code
      if: steps.golangci_config.outputs.files_exists == 'true'
      uses: golangci/golangci-lint-action@v2
      with:
        version: v1.40
        args: --timeout 3m

    - name: Test Code
      run: |
        make test

    - name: Variables
      run: |
        echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
        echo $(date -u +"BUILD_TIME=%Y-%m-%dT%T-UTC") >> $GITHUB_ENV

    - name: Info
      run: |
        echo "::debug::RELEASE_VERSION=${{ env.RELEASE_VERSION }}"

    - name: Install Ko
      uses: imjasonh/setup-ko@v0.4

    - name: Publish Image
      run: |
        KO_DOCKER_REPO=ghcr.io/$GITHUB_REPOSITORY \
          ko publish cmd/server --bare --tags ${{ env.RELEASE_VERSION }},latest
        